// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/history": {
            "get": {
                "description": "Retrieve a list of all history entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Get all history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.HistoryDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/result": {
            "post": {
                "description": "Create a new result with the given details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Create a new result",
                "parameters": [
                    {
                        "description": "Result to create",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ResultDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ResultDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/results": {
            "get": {
                "description": "Retrieve a list of all results",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Get all results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ResultDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task": {
            "post": {
                "description": "Create a new task with the given details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Create a new task",
                "parameters": [
                    {
                        "description": "Task to create",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.TaskDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.TaskDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "Retrieve a list of all tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get all tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.TaskDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.HistoryDTO": {
            "type": "object",
            "properties": {
                "history_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "task_id": {
                    "type": "string"
                },
                "task_options": {
                    "type": "string"
                },
                "task_result": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                }
            }
        },
        "github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.ResultDTO": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "contents": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "result_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "github_com_mauricetjmurphy_mr-elephant_internal_api_v1_models.TaskDTO": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://127.0.0.1:4000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Swagger Mr Elephant API",
	Description:      "This is a server R2 server listener.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
